import com.sample.model.Pump;
import com.sample.model.problems.*;
dialect  "java"



rule "rule1"
	when 
		item : Pump(item.isExitParametersCloseTo0() == true)
	then
		item.check("exitPressureBelowThreshold");
		item.check("exitFlowBelowThreshold");
		item.setExitPressureBelowThreshold(true);
		item.setExitFlowBelowThreshold(true);
end

rule "rule2"
	when
		item : Pump(item.wasChecked("highNoises")==true, item.isHighNoises()==true)
	then
		item.check("noises");
		item.setNoises(true);
end

rule "rule3"
	when
		item : Pump(item.wasChecked("lowNoises")==true, item.isLowNoises()==true)
	then
		item.check("noises");
		item.setNoises(true);
end

rule "rule4"
	when
		item : Pump(item.wasChecked("bumpNoises")==true, item.isBumpNoises()==true)
	then
		item.check("noises");
		item.setNoises(true);
end

rule "rule5"
	when 
		item : Pump(item.wasChecked("noises")==true, item.isNoises()==false)
	then
	    System.out.println("I AM HERRRREEE");
		item.check("bumpNoises");
		item.check("lowNoises");
		item.check("highNoises");
		item.setBumpNoises(false);
		item.setHighNoises(false);
		item.setLowNoises(false);
end

rule "debug"
	when
		item : Pump(item.isExitPressureBelowThreshold() == true)
	then
		System.out.println("IT IS WORKING BOIZ");
end

rule "vibrating"
    when
        item : Pump(item.isVibrating() == true)
    then
        System.out.println("");
        // fire appropriate question
end

rule "high-temperature"
	when 
		item : Pump(item.isHighTemperature() == true)
	then
		System.out.println("");
end

rule "not-vibrating"
	when
		item : Pump(item.isVibrating() == false)
	then
        System.out.println("");
end

rule "cavitation"
	when
		item : Pump(item.hasProblem("Cavitation"))
	then 
		System.out.println(Cavitation.getSolution());
end

rule "is-leaking"
	when
		item : Pump(item.isLeaking() == true)
	then
		System.out.println("Leaky");
end

rule "recirculation"
	when
		item : Pump(item.hasProblem("Recirculation"))
	then
		System.out.println(Recirculation.getSolution());
end

rule "sealsDamaged"
	when
		item : Pump(item.hasProblem("SealsDamaged"));
	then
		System.out.println(SealsDamaged.getSolution());
end

rule "rodDamaged"
	when
		item : Pump(item.hasProblem("RodDamaged"));
	then
		System.out.println(RodDamaged.getSolution());
end

rule "debris"
	when
		item : Pump(item.hasProblem("Debris"));
	then
		System.out.println(Debris.getSolution());
end

rule "propellerDamaged"
	when
		item : Pump(item.hasProblem("PropellerDamaged"));
	then
		System.out.println(PropellerDamaged.getSolution());
end

rule "bearingsDamaged"
	when
		item : Pump(item.hasProblem("BearingsDamaged"));
	then
		System.out.println(BearingsDamaged.getSolution());
end

rule "suctionBelowNPSH"
	when
		item : Pump(item.isSuctionPressureBelowNPSH())
	then
		System.out.println("It sucks way below NPSH");
end
		
		
